backend:
  name: git-gateway
  branch: master #Branch to update

media_folder: static/assets
public_folder: /assets

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - label: "Author"
        name: "author"
        widget: "string"
        default: "USFSC"
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "file", label: "File", widget: "file", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
