backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: file, lbale: File, widget: file }
      - { name: body, label: Body, widget: markdown }
